### ISSUE TITLE
An interface to delete stash content

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepogui#102]
An interface to delete stash content, utilising the function that is born from https://github.com/3drepo/3drepobouncer/issues/66

**Comment by jozefdobos** [comment]
TODO: add GUI pop-up window with selectors to delete:
- all contents of the stash ever
- only for specific revision
- web view or repo world or both

**Comment by carmenfan** [comment]
As I said on https://github.com/3drepo/3drepobouncer/issues/66

> Not sure the validity of this. Since the web can no longer generate the stash content once we move to gltf, clearing the stash content would effectively render the model unviewable.
> 
> Instead we should allow the user to re-generate the cache if needed. which is what i think should be implemented, which is already available on the controller (not as a single call, but multiple calls)
> 
> So maybe what we need is a regenerateStashContent() function on controller, which regenerates the stash content for this specific revision? probably with parameters to say whether you want to regenerate everything, or just gltf/src/repo 


Which translates to a gui pop up that ask you wehter you want to regenerate (check box):

- 3drepo stash
- gltf stash
- src stash
