### ISSUE TITLE
Add antialiasing to rendering

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#104]
Add option to enable/disable antialiasing:

QSurfaceFormat format;
...
format.setSamples(4); // antialiasing
setFormat(format); // must be called before the widget or its parent window gets shown

**Comment by carmenfan** [comment]
This potentially breaks down the current way of taking an image (using QWidget's grabFrameBuffer()). Make sure save screenshot works before closing this issue!

**Comment by jozefdobos** [comment]
Also see this: http://doc.qt.io/qt-5/qopenglframebufferobject.html#takeTexture

"If a multisample framebuffer object is used, then there is no texture and the return value from this function will be invalid. Similarly, incomplete framebuffer objects will also return 0."

Hence explicitly disable multisampling when saving the texture and reenable it back once QImage is created.

**Comment by jozefdobos** [comment]
Done.
