### ISSUE TITLE
View bson properties on commit dialog

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepogui#108]
At the point of commit, it'd be nice to be able to right click (or double click) on a highlighted entry of repo node and view the bson file in the form of json. Very much like viewing a bson in robomongo in a separate window when you go right click -> view document:

![image](https://cloud.githubusercontent.com/assets/11945337/12145957/0cf31110-b489-11e5-8976-86e2828fd7b2.png)

Def more of a development nice to have than have any use for end user, as you can inspect your bson without having to commit to a database. instead of checking it after commit -> wait -> launch robo mongo/ change tab on repo widget

**Comment by jozefdobos** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/3008807/12183347/392ebaba-b586-11e5-920b-b9f8ab8c3080.png)
