### ISSUE TITLE
Add autoinstall

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#110]

**Comment by jozefdobos** [comment]
http://doc.qt.io/qtinstallerframework/

**Comment by jozefdobos** [comment]
To create an installer, you first need to download pre-compiled binarycreator: http://download.qt.io/official_releases/qt-installer-framework/

**Comment by carmenfan** [comment]
done. If openSSL is selected, it will now launch the openSSL installer.

At the end of the installation, the user can select to install mongodb which brings them to the download site of mongo (by launching a .url file)

**Comment by carmenfan** [comment]
add in windows Visual c++ redistributable package as well as it is required for win7
