### ISSUE TITLE
3D_Repo_GUI_v1_0a_Windows_64bit.zip crashed when commit scene to the database

### ISSUE THREAD

**Issue by wsdflink** [3drepo/3drepogui#116]
I can open 3d models by using the latest release version, 3D_Repo_GUI_v1_0a_Windows_64bit.zip. And 3drepogui connecting to the local mongodb is ok. After click "commit" button, application can show item lists to store to db. But when click "ok" in "commit" dialog window, 3drepogui crashed. Anyone can help me??

**Comment by wsdflink** [comment]
![11](https://cloud.githubusercontent.com/assets/4362868/12228413/2be6b66c-b876-11e5-9f8a-9213de159ce7.png)

**Comment by jozefdobos** [comment]
Hi, Thanks for the report. You need to manually fill in the Database and Project names:

![image](https://cloud.githubusercontent.com/assets/3008807/12228773/cd2004f0-b837-11e5-98d5-e781e9646a61.png)

Please try again if this works. Either way the app should not crash so we'll fix that, ie by showing an error message telling the user info is missing.

**Comment by wsdflink** [comment]
Thanks for your reply. I have upgraded my mongodb from version 2.6 to 3.2 (The latest version). And the key step is need to add a user in the admin database for further authentication.Then login in 3drepogui and connect monodb with authentication tab filled with the corresponding user info, it can commit 3d models now. 
![13](https://cloud.githubusercontent.com/assets/4362868/12230852/04fbe1d6-b88e-11e5-8b81-bbe36f52ea9f.png)

**Comment by carmenfan** [comment]
Please be aware that we only support up to Mongo DB 3.0 as Mongo 3.2 has only come out within the past few months. You may be better off sticking with 2.6 or 3.0 for stability. For example, this release is shipped with mongo cxx client  legacy 1.0.3, and the support for Mongo 3.2 was only release last month on legacy 1.1.0

**Comment by wsdflink** [comment]
@carmenfan thanks for your information.

**Comment by carmenfan** [comment]
For clarity, I'm closing this issue and added a new issue with the specific bug (#119).

If you find any other bugs regarding commit feel free to reopen this and we can look into it further.

Thanks for trying out 3D Repo! :)
