### ISSUE TITLE
Create a super dialog class

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#16]
Many dialogs share the same functionality such as running and cancelling threads (eg History Dialog and User Manager Dialog). Hence, create a super dialog class from which others can inherit basic functionality.

**Comment by carmenfan** [comment]
Not sure if this is still relevant... i'm putting it on 1.0 beta so we consider it when we do the next release

**Comment by jozefdobos** [comment]
Nah, we should ditch this.
