### ISSUE TITLE
3drepo gui stop's working

### ISSUE THREAD

**Issue by gijskoning** [3drepo/3drepogui#171]
I had this message multiple times with different scenario's.
When i drag an ifc file into the gui it crashes. Also when clicking on head.

I downloaded and installed the newest version of 3drepo gui.
I can connect with the mongodb server
And when i add a user it does not add to the user list.

Can somoene help me with these problems?

**Comment by carmenfan** [comment]
Hi,

We will be releasing v1.2.0 of the GUI shortly, which contains several bug fixes.

I'd suggest to try out this version of the GUI first, and if the problem still persist on that version we can look into the problem further for you.

**Comment by gijskoning** [comment]
Well i have tried but with multiple errors. Do i have to install any other sofware other than the gui, mongodb and the webserver to make a complete webapplication?

Do you when the version will be out?

**Comment by jozefdobos** [comment]
No, you don't need anything else. The GUI and MongoDB can live on their own, as well as the web/API server and MongoDB. You don't necessarily need both at the same time. If you send us your IFC model to support@3drepo.org we can certainly have a look. One known issue is that if the IFC contains errors, we would not be able to process it. In terms of timing, the new version should be out within a couple of weeks.

**Comment by carmenfan** [comment]
Hi,

v1.2.0 is now available on github https://github.com/3drepo/3drepogui/releases/tag/1.2.0

Please give it a try. If it still doesn't work, please tell me about the following:

- Which operating system are you using
- The step by step instruction on how to reproduce your problem
- The file you have tried to upload (if you can share it)

Thanks.

**Comment by carmenfan** [comment]
I'm closing this ticket due to lack of response. If you incur further problems with 3D Repo GUI please feel free to re-open it with details on how to reproduce it. Thanks!
