### ISSUE TITLE
GUI crashes when trying to load MTL file

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#189]
When I accidentally dragged an MTL file to the GUI window to load instead of OBJ it crashes. However, trying to load other "unsupported" files such as JPG or sketchup results in empty 3D rendering and no crash. So there must be something really nasty about MTL!

**Comment by carmenfan** [comment]
Just tried this and I'm not seeing a crash (though arguably we should stop it from trying to import something that's not recognised.) Might need the specific MTL file you tried to see what happened there.

![image](https://cloud.githubusercontent.com/assets/11945337/20559605/4243cb0c-b16d-11e6-8cef-052eba13a863.png)

**Comment by carmenfan** [comment]
if we do #195 it should fix it
