### ISSUE TITLE
Error opening 3DrepoGUi after installing

### ISSUE THREAD

**Issue by osome** [3drepo/3drepogui#204]
After a clean installation of the last binaries on Windows 7, I have an error telling:

Ordinal 3253 not found on LIBEAY32.dll
![captura](https://cloud.githubusercontent.com/assets/542402/24318113/6df67bbc-1100-11e7-935a-c2842cd9ec2d.PNG)

**Comment by jozefdobos** [comment]
Hi Ramon, 
That means you're missing OpenSSL installation on your system. Please download and install from here: https://www.openssl.org/source/
Cheers,
Jozef
