### ISSUE TITLE
GLC_Lib

### ISSUE THREAD

**Issue by Mar-iam** [3drepo/3drepogui#205]
Hi,
I am trying to install 3D repo on my MacOS. Trying to follow the instructions on: 
https://github.com/3drepo/3drepogui
& 
https://github.com/3drepo/3drepogui/wiki/Compiling-GLC-Lib

However, I can't see tag/Version_3_3_0 in GLC_Lib. 
I installed QT5.5 to be able to run 3DRepoGUI.

Any help?

**Comment by jozefdobos** [comment]
Hi,
You can find it here: https://github.com/3drepo/GLC_lib/tree/Branch_Version_3_0_0
Cheers,
Jozef
