### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by Stinkfist0** [3drepo/3drepogui#35]
Due to the recent moving and addition of files the build seems to get broken, at least on Windows using VS 2013:
`..\3drepogui\src\widgets\repofilterabletreewidget.cpp(93) : error C2039: 'getFont' : is not a member of 'QTreeView'`

Following up on `ui->treeView` to the file `ui_repofilterabletreewidget.h` one can see that the files for the following #includes don't exist:
```
#include "../widgets/repo_clickabletreeview.h"
#include "../widgets/repo_lineedit.h"
```

This error should be easily reproducable by cleaning up the project and trying to build again.

Before pulling the latest code I was at c34a6c6766d5513db86b3fe0bfb3a9b9c8c4ae9e and it was working OK.

**Comment by jozefdobos** [comment]
Try the latest master for GUI and master for Core, it should work. Thanks!

**Comment by Stinkfist0** [comment]
Hi. The problem(s) still seem to persist. I'll get back to you when I have more time to research this.

**Comment by jozefdobos** [comment]
Ok, I'll dig into this deeper. Otso had also problem with getFont on his Mac today.
