### ISSUE TITLE
Add automated rotation for DirectX models

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#37]
Add automatic 270° rotation around X-axis for models generated in DirectX mode such as FBX

**Comment by carmenfan** [comment]
this is supported in the bouncer already https://github.com/3drepo/3drepobouncer/issues/29

The gui just need to call RepoScene::reorientateDirectXModel() at the right time

**Comment by carmenfan** [comment]
now automatically rotates if it is an fbx file
