### ISSUE TITLE
Add Qt5.5 support

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#47]
Add support for desktop OpenGL on Qt5.5. See https://blog.qt.io/blog/2014/11/27/qt-weekly-21-dynamic-opengl-implementation-loading-in-qt-5-4/ and http://doc.qt.io/qt-5/windows-requirements.html

**Comment by jozefdobos** [comment]
Carmen, pls test these changes on 5.4.2 to make sure they don't break old builds.

**Comment by carmenfan** [comment]
See #48 . merged to master and working.
