### ISSUE TITLE
Add support for GLC Lib 3.0.0

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#48]
Use 3D Repo forked branch to get it working for Qt5.5 https://github.com/3drepo/GLC_lib/tree/Branch_Version_3_0_0
since Qt now has a dynamic OpenGL selector on by default which requires desktop OpenGL flags enabled.

**Comment by jozefdobos** [comment]
Both Debug and Release work fine on Win10 on my laptop. I'll also try in the office.

**Comment by carmenfan** [comment]
considered working. Merged to master
