### ISSUE TITLE
Connecting to a different server loads previous one

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#57]
New information is passed to controller->authenticateToAdminDatabaseMongo() but it still connects to previously connected server.

**Comment by carmenfan** [comment]
This is a duplication of this https://github.com/3drepo/3drepobouncer/issues/11 (and also a bouncer issue not a gui issue)

Could implement a quick fix on this, but the question is quick fix, or actually spend a bit more time and implement the database manager?

**Comment by jozefdobos** [comment]
Ok, let's discuss the relative merits tomorrow.

**Comment by carmenfan** [comment]
As discussed, we will create the ability to disconnect and connect to another host as a quick fix 
See https://github.com/3drepo/3drepobouncer/issues/40

**Comment by carmenfan** [comment]
Should work now provided you disconnect your previous connection before instantiating the new one using the function within repocontroller:

````c++
		/**
		* Disconnect the controller from a database connection
		* and destroys the token
		* FIXME: CURRENTLY NOT THREAD SAFE! POTENTIALLY DANGEROUS
		* @param token token to the database
		*/
		void disconnectFromDatabase(const RepoToken* token);
````

Note: As the comment say it can be potentially dangerous if you have a process running something with the handler and you  have another thread trying to close it. there is no asynchonrous guarantee right now. This call should ultimately gets redirected to the database manager, who should have some form of asynchonrous lock for this kind of functions.
