### ISSUE TITLE
Users are duplicated when User manager is launched

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepogui#59]
When user manager is launched, every entry is duplicated, but if you hit refresh, it doesn't happen

Probably due to either we secretly launch 2 user workers, or we are emitting too many signals

**Comment by carmenfan** [comment]
This no longer happens on my machine for some reason....

**Comment by jozefdobos** [comment]
Still there on mine

**Comment by carmenfan** [comment]
@timscully1983  thinks it might be to do with QT dialogue (or somewhere) caching the information. When you have the time to code again can you try and see if clearing the entries first solves this?
