### ISSUE TITLE
Commit dialogue needs to be able to support large amount of nodes and not halt forever

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepogui#61]
When a massive model is being committed (with 60k+ nodes for e.g.) the gui hangs for a ridiculous amount of time as it traverse through the the entire array of nodes to display the info on the dialogue box.

**Comment by jozefdobos** [comment]
Also, launching commit dialog when no model is loaded causes crash.

**Comment by carmenfan** [comment]
Bug in commit dialogue.

Discovered during the implementation of the optimisation revival @ #66 

commit dialogue shows EVERYTHING as added, even if it was modified or deleted.

**Comment by carmenfan** [comment]
fixed and merged into master
