### ISSUE TITLE
rotation on the transformations are not being registered when the transformation is committed

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepogui#64]
when a transformation is modified in the commit dialogue, the node isn't modified.

**Comment by carmenfan** [comment]
@paloknapo  tried to rotate the rotate the root of the federated model and found it didn't work (on the commit dialogue)

@jozefdobos you disabled it on this commit: https://github.com/3drepo/3drepogui/commit/704b9baa11082af67f0ba7500fa9e6d2a6dab0c2#diff-fc66d2fe35e7e766f41233be70abd12d  What was the reason? I guess it only does the unoptimized so stash wouldn't work with this, but maybe we should disable it all together until it is fixed, or at least put a warning message saying "this operation is not supported" or something if we don't deal with it

**Comment by jozefdobos** [comment]
I think the commenting out was only due to compatibility issue (understand non-compilation) with wrong version of bouncer. This is my usual hack now fix later approach. Technically it should work just fine. Give it a shot to see if it breaks.

**Comment by jozefdobos** [comment]
We should really start unit and regression tests to prevent such breakages in the future :(

**Comment by carmenfan** [comment]
I tried it already and it worked fine, I guess the problem is changing that transformation wouldn't change the one in the stash. We need to either map it across (which may get complicated if it's not the root transformation,since the transformation is applied into the mesh on the stash) or just don't let the user do it at all.

**Comment by carmenfan** [comment]
Well I'm still trying to do my 1 day a week test day, but the progress is slow because it's only one day a week :P

**Comment by carmenfan** [comment]
As discussed, we will disable the ability to alter the transformation matrix on the commit dialogue. for FBX models the user will have to rotate it via a flag on the settings (a new issue for this to follow)
