### ISSUE TITLE
Single mesh, multiple material support

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepogui#72]
Stash graph requires one mesh with multiple materials supported to be viewed on GLC viewer

**Comment by carmenfan** [comment]
I have a vague idea how to go about doing this within GLC_Lib, without hijacking the shader. Not sure what are the performance impacts, but I'm struggling to get 3D diff to look right without this, as the original scene graph may or may not have normals meaning some meshes can't be coloured (I guess I could remove the material and colour the mesh itself... but meh)

@jozefdobos  stop me if you intend to do this soon, otherwise i'll just try to see if my way of doing it works. Then it could be a temp fix (if too slow) or maybe we don't have to hi-jack the shader at all.

**Comment by jozefdobos** [comment]
Nah, I'll look into the graphs first, we'll leave the shaders for Q1 2016.

**Comment by carmenfan** [comment]
This is done. GLC_Lib natively supports single mesh, multiple materials....
