### ISSUE TITLE
3D Diff renderer improvement

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepogui#79]
2 main things: 

<s>1 - The renderer class should only have to worry about assigning colours to differences, the actual diff should happen elsewhere. (we need a widget for this #80 ) </s>

2 - Modified/added transformations currently is not addressed in this renderer, for e.g. if a high level transformation has been modified, it effectively transformed all the meshes who are further down the line, so the entire subtree should be seen as modified even if it wasn't.

**Comment by carmenfan** [comment]
It's been discussed that the transformation changes should be indicated as some form of bounding box rendering indicating it's been moved

**Comment by jozefdobos** [comment]
Name correspondence seems to work fine

![image](https://cloud.githubusercontent.com/assets/3008807/12012437/2f64f240-aceb-11e5-999b-e05e1d6b3012.png)

however, the visualisation of turquiose should be on both models:
![image](https://cloud.githubusercontent.com/assets/3008807/12012440/45309610-aceb-11e5-86ff-83a66b164320.png)

**Comment by carmenfan** [comment]
could be to do with the colouring opacity, what if you change that from 0.9 to 1?

**Comment by carmenfan** [comment]
there was a bug with the code + opacity 0.9 is obscuring some colours by the looks of things, fixing up both gives me what we expects:

![image](https://cloud.githubusercontent.com/assets/11945337/12089295/3cd6811e-b2db-11e5-9025-fe9249610012.png)


I'll commit this and we'll stick with 1.0 opacity. Since we use 1.0 on correspondence anyway
