### ISSUE TITLE
A new widget to choose Diff algorithms

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepogui#80]
When we click on 3D Diff -> Show a widiget (or a dialogue, w/e it's suppose to be!) to allow you to choose which algorithm to apply. This should call the comparison function in the bouncer API, and display the changes with the help of 3dDiffRenderer (maybe. we may want to refactor the whole process.)

**Comment by jozefdobos** [comment]
Do we really need a widget? In the very old GUI it used to be simply 4 buttons to decide what algorithm in which layout to use. I think we need a dialog box only if you plan on having many different tweaking sigma values.

[![Old diff](http://img.youtube.com/vi/YGfpMRsue55A/0.jpg)](http://www.youtube.com/watch?v=GfpMRsue55A&t=14s)

**Comment by carmenfan** [comment]
If a dialog is enough then dialog it is. My concern is that we have nothing at the moment and it's currently hardcoded in the gui which diff mode to choose. And also the constraint of "exactly 2 windows needs to be opened" is a bit siilly.
