### ISSUE TITLE
Merge control and conflict resolution

### ISSUE THREAD

**Issue by theoryshaw** [3drepo/3drepogui#88]
For 3Drepo, do you guys have any plans on developing a merge control and conflict resolution solution similar to this? https://www.youtube.com/watch?v=hzfReQZZom8

**Comment by jozefdobos** [comment]
Hi,

Thanks for asking. I did research along similar lines a couple of years back, first assuming known correspondence as is the case of Constructivity
SIGGRAPH 2012: https://www.youtube.com/watch?v=AJkd3qZy1Xs
SIGGRAPH Asia 2012: https://www.youtube.com/watch?v=GfpMRsue55A

and more recently from unordered polygon soup inferring correspondences across vast numbers of components
Eurographics 2014: https://www.youtube.com/watch?v=oTmnm1sLf14

You can find corresponding publications at: http://3drepo.org/publications/

Cheers,
Jozef

**Comment by theoryshaw** [comment]
Very cool. Is it in the 3Drepo development roadmap to provide this type of functionality for IFC files specifically?

**Comment by jozefdobos** [comment]
Thanks! We don't restrict ourselves to IFC only and yes, eventually we'll release a statistical inference model.

**Comment by theoryshaw** [comment]
I'll be your first customer for that feature! :)  Looking forward.

@yorikvanhavre thought you might be interested in this as well. :)
