### ISSUE TITLE
Connection manager dialog not centered on first show

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#90]
Since QMainWindow is not yet drawn when the connection manager dialog is executed, it is not centered within the main window. Currently I have no idea how to fix it. Even this didn't work: http://stackoverflow.com/questions/23271423/qdialog-not-centered-on-parent

**Comment by carmenfan** [comment]
would it help if we cheat it by instead of calling it during startup(), call it after startup? 
something like this:
````c++
    repo::gui::RepoGUI w(controller);


    w.show();
    w.startup(); //remove connectDB() from startup()
    w.connectDB() //expose this so main.cpp can call it
````
